### ISSUE TITLE
Consider providing the option to dynamically install the CMP

### ISSUE THREAD

**Issue by lanzone1** [MyAgilePrivacy/gtm-templates-myagileprivacy-cmp#2]
When reviewing the template we noticed that the template is only configuring consent settings. Have you considered also providing the option to install the CMP through the template using injectScript? This helps to simplify the installation of the CMP removing the necessity for adding any on-page code and simplifying consent mode setup.

**Comment by MyAgilePrivacy** [comment]
Thank you for your message. We have indeed considered the suggestion, but we must prioritize compliance with GDPR and pre-consent blocking requirements. Installing third-party cookies should occur only after consent has been obtained, and our CMP (Consent Management Platform) enables us to enforce strict policies in this regard, employing solutions that prevent script execution without consent.

While installing through Tag Manager might seem convenient, it could potentially lead to script execution before our consent blocking mechanisms are fully functional, thereby compromising compliance. Therefore, we opt for solutions that ensure proper sequencing of actions, guaranteeing that third-party cookies are only installed post-consent.

We appreciate your input and understand the desire for simplified installation processes, but our priority remains ensuring that our practices align with legal requirements and best practices in data protection.
